###
OPTIONS  http://localhost:6060/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoiZ2FsQGdtYWlsLmNvbSIsIm5hbWUiOiJnbW9zaGtvIiwicGFzc3dvcmQiOiIkMmIkMTAkNXRQZWNJQnEyUkpOQ3hFcGwzdTR6ZW9FemJVZ09mWTd1Y3dPQmpUSjZDRWpHWWxLUWdkaWkiLCJpc0FkbWluIjp0cnVlfSwiaWF0IjoxNjAxOTk3MDg3LCJleHAiOjE2MDE5OTcxMTd9.aHzRYnW99O66Ifxe_1FRLwqfarHcNCWLYnpKWu2wNWM
